# Generated by Django 4.0.5 on 2022-07-05 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('price_sf', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rent_sf', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rent_over_value', models.DecimalField(decimal_places=3, max_digits=4)),
                ('proj_price_appreciation', models.DecimalField(decimal_places=2, max_digits=4)),
                ('proj_rent_appreciation', models.DecimalField(decimal_places=2, max_digits=4)),
                ('proj_airb_appreciation', models.DecimalField(decimal_places=2, max_digits=4)),
                ('occupancy', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('property_type', models.CharField(blank=True, max_length=50, null=True)),
                ('sqf', models.IntegerField(blank=True, null=True)),
                ('beds', models.IntegerField(blank=True, null=True)),
                ('baths', models.IntegerField(blank=True, null=True)),
                ('asking', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('cap_rate', models.FloatField(blank=True, null=True)),
                ('cash_on_cash', models.FloatField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighborhood', to='backend.area')),
            ],
        ),
    ]
