# Generated by Django 4.0.5 on 2022-06-19 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('price_sf', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rent_sf', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rent_over_value', models.DecimalField(decimal_places=2, max_digits=4)),
                ('rent_per_bed', models.DecimalField(decimal_places=2, max_digits=4)),
                ('proj_price_appreciation', models.DecimalField(decimal_places=2, max_digits=4)),
                ('proj_rent_appreciation', models.DecimalField(decimal_places=2, max_digits=4)),
                ('proj_airb_appreciation', models.DecimalField(decimal_places=2, max_digits=4)),
                ('occupancy', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('expenses_per', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Zipcode',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('price_sf', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rent_sf', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rent_over_value', models.DecimalField(decimal_places=2, max_digits=4)),
                ('rent_per_bed', models.DecimalField(decimal_places=2, max_digits=8)),
                ('proj_price_appreciation', models.DecimalField(decimal_places=2, max_digits=4)),
                ('proj_rent_appreciation', models.DecimalField(decimal_places=2, max_digits=4)),
                ('proj_airb_appreciation', models.DecimalField(decimal_places=2, max_digits=4)),
                ('occupancy', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('expenses_per', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('property_type', models.CharField(blank=True, max_length=50, null=True)),
                ('sqf', models.IntegerField(blank=True, null=True)),
                ('beds', models.IntegerField(blank=True, null=True)),
                ('baths', models.IntegerField(blank=True, null=True)),
                ('asking', models.IntegerField()),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighborhood', to='backend.neighborhood')),
                ('zipCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zip_code', to='backend.zipcode')),
            ],
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='zip_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.zipcode'),
        ),
    ]
