# Generated by Django 4.0.5 on 2022-06-19 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='rent_per_bed',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
