# Generated by Django 4.0.5 on 2022-06-20 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_property_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
