# Generated by Django 4.0.5 on 2022-06-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_property_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='proj_airb_appreciation',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='proj_price_appreciation',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='proj_rent_appreciation',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='proj_airb_appreciation',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='proj_price_appreciation',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='proj_rent_appreciation',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
    ]
