# Generated by Django 4.0.5 on 2022-06-20 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_neighborhood_proj_airb_appreciation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhood',
            name='expenses_per',
        ),
        migrations.RemoveField(
            model_name='zipcode',
            name='expenses_per',
        ),
    ]
