# Generated by Django 4.0.5 on 2022-06-20 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_neighborhood_occupancy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhood',
            name='zip_code',
        ),
    ]
