# Generated by Django 4.0.5 on 2022-06-20 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_rename_zipcode_property_zipcode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Zipcode',
            new_name='Area',
        ),
        migrations.RenameField(
            model_name='area',
            old_name='code',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='property',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='property',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.ForeignKey(default=70125, on_delete=django.db.models.deletion.CASCADE, related_name='neighborhood', to='backend.area'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Neighborhood',
        ),
    ]
