# Generated by Django 4.0.5 on 2022-06-22 20:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_rename_zipcode_area_rename_code_area_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='rent_per_bed',
        ),
        migrations.AddField(
            model_name='property',
            name='zip_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='area',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
    ]
