# Generated by Django 4.0.5 on 2022-06-23 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_remove_area_rent_per_bed_property_zip_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='active',
        ),
        migrations.AddField(
            model_name='property',
            name='user',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
