# Generated by Django 4.0.5 on 2022-06-23 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_rename_user_property_usermade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='userMade',
        ),
    ]
