# Generated by Django 4.0.5 on 2022-06-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_remove_property_usermade'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='cap_rate',
            field=models.DecimalField(decimal_places=4, default=10.01, max_digits=6),
            preserve_default=False,
        ),
    ]
