# Generated by Django 4.0.5 on 2022-06-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_property_cap_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='cap_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
