# Generated by Django 4.0.5 on 2022-06-24 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_alter_property_cap_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='cash_on_cash',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
