# Generated by Django 4.0.5 on 2022-06-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_property_cash_on_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='occupancy',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='area',
            name='price_sf',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='area',
            name='proj_airb_appreciation',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='area',
            name='proj_price_appreciation',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='area',
            name='proj_rent_appreciation',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='area',
            name='rent_over_value',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
        migrations.AlterField(
            model_name='area',
            name='rent_sf',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='area',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
